language: node_js
node_js:
- '8'
install:
- npm install -g git+https://github.com/datahq/data-cli.git
script: data push sample.csv --name=sample
env:
  global:
    id: examples
    username: examples
  TRAVIS_SECURE_ENV_VARS: true
